name: 'Pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/test
        with:
          codacy-api-token: ${{ secrets.CODACY_API_TOKEN }}
