name: 'Release 🚀'

on:
  push:
    branches:
      - alpha
      - beta
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/test
        with:
          codacy-api-token: ${{ secrets.CODACY_API_TOKEN }}

  release:
    name: 'Publish new release 🚀'
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/yarn-install@v3

      - name: 'Create build'
        run: yarn build

      - uses: myparcelnl/actions/semantic-release@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
