name: 'Release 🚀'

on:
  push:
    branches:
      - alpha
      - beta

jobs:
  release:
    name: 'Publish new release 🚀'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/yarn2-install@v2

      - name: 'Create build'
        run: yarn build

      - uses: myparcelnl/actions/semantic-release@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
